### ISSUE TITLE
115增加标签接口

### ISSUE THREAD

**Issue by wangzhenyang** [ChenyangGao/web-mount-packs#1]
115已经实现了星标接口，希望可以增加标签接口。
标签用起来类似于playlist，可以创建多个标签对视频的小系列进行区分。
很使用的功能，希望可以支持。

**Comment by ChenyangGao** [comment]
> 115已经实现了星标接口，希望可以增加标签接口。 标签用起来类似于playlist，可以创建多个标签对视频的小系列进行区分。 很使用的功能，希望可以支持。

<img width="733" alt="截屏2023-12-12 17 14 20" src="https://github.com/ChenyangGao/web-mount-packs/assets/26198875/fd6dc958-b33f-4828-97a3-9a2478cb7df9">

你好，其实我早就实现了，但没有做文档，所以你不知道
https://github.com/ChenyangGao/web-mount-packs/blob/main/python-115-client/p115/__init__.py#L541

**Comment by wangzhenyang** [comment]
调用 POST https://webapi.115.com/files/edit， comment_set接口：

fid = fs.attr[$filepath]['id']
payload = {}
payload['fid'] = fid
payload['file_label'] = $label_id
client.comment_set(payload=payload)


作者有时间，可以帮忙实现一下 https://webapi.115.com/label/list接口，通过label name反查label_id。

**Comment by ChenyangGao** [comment]
> 调用 POST https://webapi.115.com/files/edit， comment_set接口：
> 
> fid = fs.attr[$filepath]['id']
> payload = {}
> payload['fid'] = fid
> payload['file_label'] = $label_id
> client.comment_set(payload=payload)
> 
> 
> 作者有时间，可以帮忙实现一下 https://webapi.115.com/label/list接口，通过label name反查label_id。
> 

好的

**Comment by ChenyangGao** [comment]
https://github.com/ChenyangGao/web-mount-packs/blob/0b8e1ac42be81b3a1c21037511f0a024aa9a806d/python-115-client/p115/__init__.py#L677
你好，增加了好几个关于 label 的接口
- P115Client.label_add 添加标签（可以接受多个）
- P115Client.label_del 删除标签
- P115Client.label_edit 编辑标签
- P115Client.label_list 罗列标签列表（如果要获取做了标签的文件列表，用 `fs_search` 接口）
- P115Client.label_set 为文件或文件夹设置标签，此接口是对 `fs_files_edit` 的封装
- P115Client.label_batch 批量设置标签
