### ISSUE TITLE
请求新增115网盘功能

### ISSUE THREAD

**Issue by jack-master** [ChenyangGao/web-mount-packs#15]
1、新增许愿相关功能：
    1). wish_make(cookie1, content, size):
      输入：content为许愿内容，size答谢的空间大小；
      输出：wish_id，为愿望的id，6位字母
    2). wish_answer(**cookie2**, content, wish_id):
      输入：content为回答内容，wish_id为要回答的愿望ID，6位字母
    3). wish_list(cookie1)
       查看所有已许愿，包含已完成和未完成
    4). wish_adopt(cookie1, answer_id)
      如果answer_id是我大号的账号ID，就采纳

**以上cookie1为小号许愿账号，cookie2为大号答复账号，效果是让小号送空间给大号**
      
2、批量重命名、批量移动
    就像网页版那样

感谢大佬！

**Comment by ChenyangGao** [comment]
批量重命名之类的已做，只是文档好久没更新，那个许愿树我再了解一番，没看到哪有这个功能，你截几张图片，我好知道这个功能在哪

**Comment by ChenyangGao** [comment]
P115Client.fs_batch_*都是批量操作方法
P115Client.fs_batch_copy         批量复制
P115Client.fs_batch_delete       批量删除
P115Client.fs_batch_move        批量移动
P115Client.fs_batch_rename    批量重命名
另外还有一个
P115Client.recyclebin_revert    批量从垃圾站还原

P115FileSystem也直接使用这一个fs_batch_*方法
P115FileSystem.fs_batch_copy         批量复制
P115FileSystem.fs_batch_delete       批量删除
P115FileSystem.fs_batch_move        批量移动
P115FileSystem.fs_batch_rename    批量重命名

如果你要批量重命名，可以这样做
```python
from itertools import islice
from p115 import P115Client

client = P115Client("115的cookies")
fs = client.fs
def make_new_name(old_name):
    new_name = "对 old_name 的一些字符串处理"
    return new_name
it = fs.iter("要搜索的目录", min_depth=1, max_depth=-1, predicate=lambda p: p.is_file())
while (batch := tuple(islice(it, 1000))): # 1000 个为一批，只要 5 万个以内都可以，数字建议不要太大
    fs.fs_batch_rename((path.id, make_new_name(path,name)) for path in batch)
```

**Comment by ChenyangGao** [comment]
首先进行更新
```console
pip install -U 'python-115>=0.0.8.7'
```
然后导入工具函数
```python
from p115.tool import wish_make, wish_answer, wish_list, wish_aid_list, wish_adopt
```
具体可以查看函数的帮助信息

**Comment by jack-master** [comment]
感谢大佬，真是有求必应！

**Comment by jack-master** [comment]
测试了wish_make，wish_answer，wish_list三个函数
wish_make，wish_list运行起来很丝滑，
但是wish_answer好像出了一些问题，不知道是不是请求头是“application/x-www-form-urlencoded”造成的，最下方是错误代码。
如果测试用的cookie不够请联系我，我有很多账号

错误提示：
wish_answer(cookie6, wish_id="FF6VYX", content="this_is_a_test")
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/p115/tool/__init__.py", line 185, in wish_answer
    return check_response(
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/p115/component/client.py", line 141, in check_response
    return check(fn)
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/p115/component/client.py", line 139, in check
    raise OSError(errno.EIO, resp)
OSError: [Errno 5] {'state': 0, 'code': 40100000, 'message': '参数错误！', 'data': {}}

**Comment by ChenyangGao** [comment]
可以，加我微信，jin-ping_mei，确实需要两个账号的cookie
