### ISSUE TITLE
115下载文件接口

### ISSUE THREAD

**Issue by wangzhenyang** [ChenyangGao/web-mount-packs#17]
尝试用 fs.download 通过 路径 和 id 下载文件，都失败了，请问怎么解决？

fs.download(path)
<DownloadTask :: state='FAILED' progress=None>

id = fs.attr(path)['id']
fs.download(id)
<DownloadTask :: state='FAILED' progress=None>

上面版本是0.0.8.4，刚才测试了一下旧版本0.0.4可以正常下载

**Comment by ChenyangGao** [comment]
好了，更新一下
```console
pip install -U 'python-115>=0.0.8.7.4'
```
