### ISSUE TITLE
rename会生成空文件夹

### ISSUE THREAD

**Issue by jack-master** [ChenyangGao/web-mount-packs#18]
更新最近的版本以后，rename的时候会生成空文件夹。

file_path = "/我的接收"
fs.chdir(file_path)
old_name = fs.listdir()[0]
new_name = old_name + ".mkv"
fs.rename(old_name, new_name)

生成了"/我的接收/我的接收"空文件夹

**Comment by ChenyangGao** [comment]
已修复，更新一下即可
```console
pip install -U 'python-115>=0.0.8.8'
```
