### ISSUE TITLE
请求python-115兼容python 3.9

### ISSUE THREAD

**Issue by Alano-i** [ChenyangGao/web-mount-packs#2]
请问此封装能否对 python 3.9 做个兼容。如果可以那将太好了。

**Comment by ChenyangGao** [comment]
3.9比较旧了，因此不支持

**Comment by ChenyangGao** [comment]
3.12其实才是我一开始计划支持的版本，早在3.12正式版还没发布之前

**Comment by Alano-i** [comment]
倒不是win7，正在用一个追剧的项目，他用了.so
升python版本会影响到自动下载和一些其他功能。
本想基于你这个封装做个115插件，如果兼容3.9不在计划中也只好作罢了。还是感谢解答。

**Comment by Alano-i** [comment]
我用的那个追剧下载是指追剧相关的从站点下载到本地，不是下载115里的文件。

此 115 的 API 封装若下载源码到本地是否可以在python 3.9环境中运行？
