### ISSUE TITLE
AlistPath的__str__方法在不同平台出现的结果可能不同

### ISSUE THREAD

**Issue by Akimio521** [ChenyangGao/web-mount-packs#22]
在Windows平台下
alist_path:AlistPath = ...
str(alist_path)，这个字符串不会以`/`开头
但是在某些Linux环境下，str(alist_path)，这个字符串会以`/`开头
具体情况未知，在WIndows的WSL中的docker里又不会以`/`开头

**Comment by Akimio521** [comment]
均为Python 3.11.9

**Comment by ChenyangGao** [comment]
好的
