### ISSUE TITLE
请问是否有上传文件夹的方法？

### ISSUE THREAD

**Issue by BlackWhite2000** [ChenyangGao/web-mount-packs#30]
找了下只找到了上传文件

**Comment by ChenyangGao** [comment]
upload_tree

**Comment by BlackWhite2000** [comment]
请问下，这个false是为了避免什么问题吗

```
if False:
    from .component import *
```

因为加了false后，如果 from p115 import P115Client, P115FileSystem 会导致函数无法高亮提示。
这时候想看有什么函数有点不太直观，试了删除没有什么报错出现

**Comment by ChenyangGao** [comment]
删了以后就可以高亮么？

**Comment by BlackWhite2000** [comment]
对，删除前：
![2](https://github.com/user-attachments/assets/bd48211d-5960-44e4-b330-ae114187566b)
![3](https://github.com/user-attachments/assets/aa9ef9d9-dda1-4a36-9499-216b7543f7f1)

删除后：
![4](https://github.com/user-attachments/assets/2870f17f-1a79-4c89-a656-9f79e2dfcac1)
![1](https://github.com/user-attachments/assets/31ed194a-2234-46cc-8ae2-928a1d5876b7)

**Comment by ChenyangGao** [comment]
好的，那我删了

**Comment by ChenyangGao** [comment]
你可以用命令行
p115 upload

**Comment by BlackWhite2000** [comment]
发现一件很神奇的事情。。
这样写无法上传目录
```
fs.upload_tree(data_dir)
```
这样写就上传成功了。。只是多了print
```
z = fs.upload_tree(data_dir)
print(list(z))
```

**Comment by ChenyangGao** [comment]
> 发现一件很神奇的事情。。
> 这样写无法上传目录
> ```
> fs.upload_tree(data_dir)
> ```
> 这样写就上传成功了。。只是多了print
> ```
> z = fs.upload_tree(data_dir)
> print(list(z))
> ```

返回的是迭代器，你还是用命令行那个，有进度条和统计信息

**Comment by BlackWhite2000** [comment]
哦这样，好。感谢
