### ISSUE TITLE
如果删掉 from .component import *  vscode代码高亮会失效

### ISSUE THREAD

**Issue by BlackWhite2000** [ChenyangGao/web-mount-packs#31]
问题：https://github.com/ChenyangGao/web-mount-packs/commit/89f43d95ceb522003d74b3ad2145d0371fdb8414#r144225810

**Comment by BlackWhite2000** [comment]
https://github.com/ChenyangGao/web-mount-packs/issues/30#issuecomment-2227330324
此处指的是删除 if False 而不是引用

**Comment by ChenyangGao** [comment]
好的
