### ISSUE TITLE
请问115API是否有获取当前目录下所有文件数量的方法？

### ISSUE THREAD

**Issue by BlackWhite2000** [ChenyangGao/web-mount-packs#33]
只找到了dirlen，也就是当前目录下的文件数量，而不是当前目录下包括子目录下的所有文件数量
我是写了个递归，通过切换 `self.fs.chdir(dir_path_item)` 实现统计。
但是这存在一个问题，切换次数过多好像115会限制
```
httpx.HTTPStatusError: Client error '405 Not Allowed' for url 'https://webapi.115.com/files/getid?path=files'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
```

**Comment by ChenyangGao** [comment]
client.fs_files_statistic

**Comment by BlackWhite2000** [comment]
> client.fs_files_statistic

你好，在 client.py 里面我好像没找到 fs_files_statistic

**Comment by BlackWhite2000** [comment]
找到了  `fs_statistic`

**Comment by ChenyangGao** [comment]
> 找到了  `fs_statistic`

对，是这个

**Comment by NotHFN** [comment]
> > 找到了  `fs_statistic`
> 
> 对，是这个

这个函数好像又没了，请问现在是哪个函数呢？
