### ISSUE TITLE
请问upload_tree有没有增加同时上传文件数的方法

### ISSUE THREAD

**Issue by BlackWhite2000** [ChenyangGao/web-mount-packs#35]
因为我发现115使用 `upload_tree` 的时候好像会限速。
本该20mb以上的上传速度结果却是2mb以下
可能115有限速，所以想干脆增加同时上传文件数
其实也可以同时执行多次脚本任务，但是因为电脑容量有限所以想看能不能直接修改 `upload_tree`

**Comment by ChenyangGao** [comment]
直接命令行使用
p115 upload
命令上传即可
