### ISSUE TITLE
httpx_request模块报错

### ISSUE THREAD

**Issue by qicfan** [ChenyangGao/web-mount-packs#59]
`from httpx._types import AuthTypes, CertTypes, ProxyTypes, ProxiesTypes, SyncByteStream, URLTypes, VerifyTypes`
其中ProxiesTypes和VerifyTypes在httpx.types中没有找到，导致运行报错。

目前是删除了ProxiesTypes，添加了VerifyTypes定义来解决：
`type VerifyTypes = ssl.SSLContext | str | bool`

版本：httpx = 0.28.0

**Comment by ChenyangGao** [comment]
pip install -U httpx_request
