### ISSUE TITLE
遍历了一下目录就报错

### ISSUE THREAD

**Issue by Joevaen** [ChenyangGao/web-mount-packs#8]
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://webapi.115.com/files?aid=1&asc=1&cid=0&count_folders=1&limit=1024&o=file_name&offset=0&record_open_time=1&show_dir=1

连我网页端都进不去了

**Comment by ChenyangGao** [comment]
你是多线程罗列目录了吧，会有这个问题，115限制了

**Comment by ChenyangGao** [comment]
就罗列目录的接口不能多线程，甚至也不能一秒内调用很多次，这是115的限制，你可以开启一下缓存
```python
P115FileSystem(client, path_to_id={}, attr_cache={}
```
不过这会导致内存使用量飙升

**Comment by ChenyangGao** [comment]
你也可以自己构建一个缓存，推荐用这个模块

https://pypi.org/project/cachetools/

用里面的 `LRUCache(maxsize=1000)` 就限制缓存的内存用量

然后 `P115FileSystem`，还有一些 fs_ 开头的方法，这些不能接受路径，只接受 id，用这些底层方法，可以大大减少接口调用
